Consume-Api/PB102-Consume/Areas/Admin/ViewModels/Cities/CityCreateVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using PB102_Consume.Areas.Admin.ViewModels.Countries;
using System.ComponentModel.DataAnnotations;

namespace PB102_Consume.Areas.Admin.ViewModels.Cities
{
    public class CityCreateVM
    {
        [Required]
        public string Name { get; set; }
        [Required]
        public int CountryId { get; set; }

    }
}

Consume-Api/PB102-Consume/Areas/Admin/ViewModels/Cities/CityVM.cs
namespace PB102_Consume.Areas.Admin.ViewModels.Cities
{
    public class CityVM
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string CountryName { get; set; }
    }
}

Consume-Api/PB102-Consume/Models/City.cs
namespace PB102_Consume.Models
{
    public class City
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int CountryId { get; set; }
        public Country Country { get; set; }
    }
}

Consume-Api/PB102-Consume/Areas/Admin/Controllers/CityController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PB102_Consume.Areas.Admin.ViewModels.Cities;
using System.Text;

namespace PB102_Consume.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CityController : Controller
    {
        private readonly string BaseURl = "https://localhost:7001";
        public async Task<IActionResult> Index()
        {
            IEnumerable<CityVM> cities = null;
            using (var httpClient = new HttpClient())
            { 
                using (var response = await httpClient.GetAsync($"{BaseURl}/api/City/GetAll"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    cities = JsonConvert.DeserializeObject<IEnumerable<CityVM>>(apiResponse);
                }
            }
            return View(cities);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CityCreateVM request)
        {
            if (!ModelState.IsValid)
            {
                return View(request);
            }

            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(request), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PostAsync($"{BaseURl}/api/city/create", content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }
            }
            return RedirectToAction(nameof(Index));
        }



        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.DeleteAsync($"{BaseURl}/api/city/delete/" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }
            }

            return RedirectToAction(nameof(Index));
        }

        

        [HttpGet]
        public async Task<IActionResult> Detail(int id)
        {
            CityVM city = null;
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"{BaseURl}/api/city/getbyid/" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    city = JsonConvert.DeserializeObject<CityVM>(apiResponse);
                }
            }

            return View(city);
        }
    }
}

Consume-Api/PB102-Consume/Areas/Admin/Views/City/Create.cshtml
@model CityCreateVM

<div class="container mt-5">
    <h1 class="text-center">Create City</h1>
</div>
<form class="mt-3" asp-controller="City" asp-action="Create" method="post">
    <div class="form-group">
        <label for="city">City Name</label>
        <input asp-for="Name" class="form-control" id="city">
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>

    <div class="form-group">
        <label for="countryId">Country ID</label>
        <input asp-for="CountryId" class="form-control" id="countryId" type="number">
        <span class="text-danger" asp-validation-for="CountryId"></span>
    </div>

    <button type="submit" class="btn btn-primary">Create</button>
</form>

Consume-Api/PB102-Consume/Areas/Admin/Views/City/Detail.cshtml
@model CityVM

<div class="container mt-5">
    <h1 class="text-center">Country Detail</h1>
</div>

<div class="d-flex">
    <h1>Name:</h1>
    <h1>@Model.Name</h1>
</div>

<div class="d-flex">
    <h1>Country:</h1>
    <h1>@Model.CountryName</h1>
</div>

Consume-Api/PB102-Consume/Areas/Admin/Views/City/Index.cshtml
@model IEnumerable<CityVM>

<div class="container-fluid">

    <!-- Page Heading -->
    <a class="btn btn-success" asp-controller="City" asp-action="Create">Create City</a>

    <!-- DataTales Example -->
    <div class="card shadow mb-4 mt-3">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Country</th>
                            <th>Options</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Name</td>
                                <td>@item.CountryName</td>
                                <td>
                                    <a class="btn btn-primary" asp-action="Detail" asp-route-id="@item.Id">Detail</a>

                                    <a class="btn btn-secondary" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                                    <form asp-action="Delete" asp-route-id="@item.Id" method="post" class="d-inline">
                                        <button type="submit" class="btn btn-danger">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>