Consume-Api/PB102-Consume/Areas/Admin/ViewModels/Author/AuthorCreateVM.cs
using System.ComponentModel.DataAnnotations;

namespace PB102_Consume.Areas.Admin.ViewModels.Author
{
    public class AuthorCreateVM
    {
        [Required]
        public string Name { get; set; }

        [Required]
        public string Surname { get; set; }

        [Range(0, 120)]
        public int Age { get; set; }

        public IFormFile Image { get; set; }
    }

}

Consume-Api/PB102-Consume/Areas/Admin/ViewModels/Author/AuthorVM.cs
namespace PB102_Consume.Areas.Admin.ViewModels.Author
{
    public class AuthorVM
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int Age { get; set; }
        public string Image { get; set; }
    }
}

Consume-Api/PB102-Consume/Areas/Admin/Controllers/AuthorController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PB102_Consume.Areas.Admin.ViewModels.Author;
using PB102_Consume.Areas.Admin.ViewModels.Books;
using System.Text;

namespace PB102_Consume.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AuthorController : Controller
    {
        private readonly string BaseURl = "https://localhost:7001";
        public async Task<IActionResult> Index()
        {
            IEnumerable<AuthorVM> author = null;
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"{BaseURl}/api/Author/GetAll"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    author = JsonConvert.DeserializeObject<IEnumerable<AuthorVM>>(apiResponse);
                }
            }
            return View(author);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.DeleteAsync($"{BaseURl}/api/author/delete/" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }
            }
            return RedirectToAction(nameof(Index));
        }



        [HttpGet]
        public async Task<IActionResult> Detail(int id)
        {
            AuthorVM author = null;
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"{BaseURl}/api/author/getbyid/" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    author = JsonConvert.DeserializeObject<AuthorVM>(apiResponse);
                }
            }

            return View(author);
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AuthorCreateVM request)
        {
            if (!ModelState.IsValid)
            {
                return View(request);
            }

            using (var httpClient = new HttpClient())
            {
                using (var multipartContent = new MultipartFormDataContent())
                {
                    multipartContent.Add(new StringContent(request.Name), "Name");
                    multipartContent.Add(new StringContent(request.Surname), "Surname");
                    multipartContent.Add(new StringContent(request.Age.ToString()), "Age");

                    if (request.Image != null)
                    {
                        var fileContent = new StreamContent(request.Image.OpenReadStream());
                        fileContent.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue(request.Image.ContentType);
                        multipartContent.Add(fileContent, "Image", request.Image.FileName);
                    }

                    using (var response = await httpClient.PostAsync($"{BaseURl}/api/author/create", multipartContent))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        if (!response.IsSuccessStatusCode)
                        {
                            ModelState.AddModelError(string.Empty, "API-də xəta baş verdi.");
                            return View(request);
                        }
                    }
                }
            }

            return RedirectToAction(nameof(Index));
        }



        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            BookVM book = null;
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"{BaseURl}/api/book/getbyid/" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    book = JsonConvert.DeserializeObject<BookVM>(apiResponse);
                }
            }

            return View(new BookEditVM { Id = book.Id, Name = book.Name, PageCount = book.PageCount });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, BookEditVM request)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(request), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PutAsync($"{BaseURl}/api/book/edit/{id}", content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }
            }

            return RedirectToAction(nameof(Index));

        }
    }
}

Consume-Api/PB102-Consume/Areas/Admin/Views/Author/Create.cshtml
@model AuthorCreateVM

<div class="container mt-5">
    <h1 class="text-center">Create Author</h1>
</div>

<form method="post" enctype="multipart/form-data" asp-controller="Author" asp-action="Create">
    <div class="form-group">
        <label for="name">Name</label>
        <input asp-for="Name" class="form-control" id="name">
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>

    <div class="form-group">
        <label for="surname">Surname</label>
        <input asp-for="Surname" class="form-control" id="surname">
        <span class="text-danger" asp-validation-for="Surname"></span>
    </div>

    <div class="form-group">
        <label for="age">Age</label>
        <input type="number" asp-for="Age" min="0" max="120" class="form-control" id="age">
        <span class="text-danger" asp-validation-for="Age"></span>
    </div>

    <div class="form-group">
        <label for="photo">Image</label>
        <input type="file" asp-for="Image" class="form-control" id="photo">
        <span class="text-danger" asp-validation-for="Image"></span>
    </div>

    <button type="submit" class="btn btn-primary">Create</button>
</form>

Consume-Api/PB102-Consume/Areas/Admin/Views/Author/Detail.cshtml
@model AuthorVM

<div class="container mt-5">
    <h1 class="text-center">Author detail</h1>
</div>

<div>
    <h1>Fullname: @Model.Name @Model.Surname</h1>
    <h1>Age: @Model.Age</h1>
    <h1>Image: <img src="~/../wwwroot/img/@Model.Image" alt="Alternate Text" /></h1>
</div>

Consume-Api/PB102-Consume/Areas/Admin/Views/Author/Index.cshtml
@model IEnumerable<AuthorVM>

<div class="container-fluid">

    <!-- Page Heading -->
    <a class="btn btn-success" asp-controller="Author" asp-action="Create">Add Author</a>

    <!-- DataTales Example -->
    <div class="card shadow mb-4 mt-3">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Surname</th>
                            <th>Age</th>
                            <th>Image</th>
                            <th>Options</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Name</td>
                                <td>@item.Surname</td>
                                <td>@item.Age</td>
                                <td><img src="@item.Image" style="width:150px; height:100px" /></td>
                                <td>
                                    <a class="btn btn-primary" asp-action="Detail" asp-route-id="@item.Id">Detail</a>

                                    <a class="btn btn-secondary" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                                    <form asp-action="Delete" asp-route-id="@item.Id" method="post" class="d-inline">
                                        <button type="submit" class="btn btn-danger">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>