Consume-Api/PB102-Consume/Areas/Admin/ViewModels/Countries/CountryCreateVM.cs
using System.ComponentModel.DataAnnotations;

namespace PB102_Consume.Areas.Admin.ViewModels.Countries
{
    public class CountryCreateVM
    {
        [Required]
        public string Name { get; set; }
        [Required]
        public int Population { get; set; }
    }
}

Consume-Api/PB102-Consume/Areas/Admin/ViewModels/Countries/CountryEditVM.cs
using System.ComponentModel.DataAnnotations;

namespace PB102_Consume.Areas.Admin.ViewModels.Countries
{
    public class CountryEditVM
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public int? Population { get; set; }
    }
}

Consume-Api/PB102-Consume/Areas/Admin/ViewModels/Countries/CountryVM.cs
namespace PB102_Consume.Areas.Admin.ViewModels.Countries
{
    public class CountryVM
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int? Population { get; set; }
    }
}

Consume-Api/PB102-Consume/Models/Country.cs
namespace PB102_Consume.Models
{
    public class Country
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int? Population { get; set; }
        public ICollection<City> Cities { get; set; }
    }
}

Consume-Api/PB102-Consume/Areas/Admin/Controllers/CountryController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PB102_Consume.Areas.Admin.ViewModels.Countries;
using PB102_Consume.Models;
using System.Diagnostics.Metrics;
using System.Text;

namespace PB102_Consume.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CountryController : Controller
    {
        private readonly string BaseURl = "https://localhost:7001";
        public async Task<IActionResult> Index()
        {
            IEnumerable<CountryVM> countries = null;
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"{BaseURl}/api/country/getall"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    countries = JsonConvert.DeserializeObject<IEnumerable<CountryVM>>(apiResponse);
                }
            }
            return View(countries);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CountryCreateVM request)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(request), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PostAsync($"{BaseURl}/api/country/create", content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }
            }

            return RedirectToAction(nameof(Index));

        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.DeleteAsync($"{BaseURl}/api/country/delete/" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            CountryVM country = null;
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"{BaseURl}/api/country/getbyid/" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    country = JsonConvert.DeserializeObject<CountryVM>(apiResponse);
                }
            }

            return View(new CountryEditVM { Id = country.Id, Name = country.Name, Population = country.Population });
        } 

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CountryEditVM request)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }



            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(request), Encoding.UTF8, "application/json");

                using (var response = await httpClient.PutAsync($"{BaseURl}/api/country/edit/{id}", content))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                }
            }

            return RedirectToAction(nameof(Index));

        }

        [HttpGet]
        public async Task<IActionResult> Detail(int id)
        {
            CountryVM country = null;
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"{BaseURl}/api/country/getbyid/" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    country = JsonConvert.DeserializeObject<CountryVM>(apiResponse);
                }
            }

            return View(country);
        }
        [HttpGet]
        public async Task<IActionResult> Search(CountryVM request)
        {
            IEnumerable<CountryVM> countries = null;
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"{BaseURl}/api/country/search/" + request.Name))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    countries = JsonConvert.DeserializeObject<IEnumerable<CountryVM>>(apiResponse);
                }
            }
            return View(countries);
            
        }
    }
}

Consume-Api/PB102-Consume/Areas/Admin/Views/Country/Create.cshtml
@model CountryCreateVM
<div class="container mt-5">
    <h1 class="text-center">Country</h1>
</div>
<form class="mt-3" asp-controller="Country" asp-action="Create">
    <div class="form-group">
        <label for="country">Name</label>
        <input asp-for="Name" class="form-control" id="country">
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
        <label for="population">Population</label>
        <input asp-for="Population" min="0" class="form-control" id="population">
        <span class="text-danger" asp-validation-for="Population"></span>
    </div>
    
    <button type="submit" class="btn btn-primary">Create</button>
</form>

Consume-Api/PB102-Consume/Areas/Admin/Views/Country/Detail.cshtml
@model CountryVM

<div class="container mt-5">
    <h1 class="text-center">Country Detail</h1>
</div>

<div class="d-flex">
    <h1>Name:</h1>
    <h1>@Model.Name</h1>
</div>

<div class="d-flex">
    <h1>Population:</h1>
    <h1>@Model.Population</h1>
</div>

Consume-Api/PB102-Consume/Areas/Admin/Views/Country/Edit.cshtml
@model CountryEditVM
<div class="container mt-5">
    <h1 class="text-center">Country</h1>
</div>
<form class="mt-3" asp-controller="Country" asp-action="Edit" asp-route-id="@Model.Id">
    <div class="form-group">
        <label for="country">Name</label>
        <input asp-for="Name" class="form-control" id="country">
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
        <label for="population">Population</label>
        <input asp-for="Population" min="0" class="form-control" id="population">
        <span class="text-danger" asp-validation-for="Population"></span>
    </div>

    <button type="submit" class="btn btn-primary">Edit</button>
</form>

Consume-Api/PB102-Consume/Areas/Admin/Views/Country/Index.cshtml
@model IEnumerable<CountryVM>

<div class="container-fluid">

    <!-- Page Heading -->
    <a class="btn btn-success" asp-controller="Country" asp-action="Create">Create Country</a>

    <!-- DataTales Example -->
    <div class="card shadow mb-4 mt-3">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Population</th>
                            <th>Options</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Name</td>
                                <td>@item.Population</td>
                                <td>
                                    <a class="btn btn-primary" asp-action="Detail" asp-route-id="@item.Id">Detail</a>

                                    <a class="btn btn-secondary" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                                    <form asp-action="Delete" asp-route-id="@item.Id" method="post" class="d-inline">
                                        <button type="submit" class="btn btn-danger">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>